os: linux
dist: trusty
sudo: required
language: go
go:
  - 1.10.x

cache:
  directories:
    - $HOME/faktory/vendor

before_script:
  - mkdir -p $HOME/faktory
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/faktory/
  - mkdir -p $GOPATH/src/github.com/contribsys && ln -s $HOME/faktory $GOPATH/src/github.com/contribsys/faktory
  - cd $GOPATH/src/github.com/contribsys/faktory && make prepare

script: cd $GOPATH/src/github.com/contribsys/faktory && make all
